In [3]:
import pandas as pd
df1=pd.read_csv('orders_1.csv')
df2=pd.read_csv('orders_2.csv')
df3=pd.read_csv('orders_3.csv')
df1

   order_id product  quantity
0         1       A         2
1         2       B         1
2         3       C         4

In [4]:
df2

   order_id product  quantity
0         4       A         3
1         5       B         2
2         6       D         1

In [5]:
df3

   order_id product  quantity
0         7       C         2
1         8       A         1
2         9       D         3

In [6]:
df=pd.concat([df1,df2,df3])
df

   order_id product  quantity
0         1       A         2
1         2       B         1
2         3       C         4
0         4       A         3
1         5       B         2
2         6       D         1
0         7       C         2
1         8       A         1
2         9       D         3

In [8]:
df4 = df.groupby('product')['quantity'].sum().reset_index()
df4

  product  quantity
0       A         6
1       B         3
2       C         6
3       D         4

In [13]:
df4.to_csv('product_quantities.csv', index=False)